### ISSUE TITLE
It should be possible to configure cache for each webservice individually

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/dbc-node-serviceprovider#1]
Currently cache is configured for all webserivce-client at once.
Having one global default cache configuration is fine but along with the configuration parameters for each webservice it should be possible to define cache settings for that specific webservice.

I.e.:
```javascript
opensearch: {
    wsdl: 'http://ml-p01.dbc.dk/opensearch/tags/3.2/opensearch.wsdl',
    agency: '150013',
    profile: 'opac',
    cache: {
      enabled: true,
      ttl: 3600, // seconds
      etc ...
      }
  },
```

This will require some refactoring in `registerServiceClient(config, client)` (found in ServiceClients.js).

**Comment by guddo** [comment]
Did you make any pros/cons-thoughts whether this should be defined within the service-providers config, or in the actual client?

**Comment by hrmoller** [comment]
First of I thought about defining it in the ServiceProviders config, simply because it will fulfill our current needs and because it's the solution that requires the smallest amount of work.

**Comment by guddo** [comment]
I think thats a good idea for now. If needed, we can re-open this issue later.

**Comment by hrmoller** [comment]
Fixed with https://github.com/DBCDK/dbc-node-serviceprovider/commit/7937e4ce97522e8ab5ea9a1882c75e83dca8bc53
