### ISSUE TITLE
It should be possible to use the ServiceProvider without configuring each service

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/dbc-node-serviceprovider#3]
The ServiceProvider needs each client it implements to be configured, otherwise an error will be thrown. This should be changed so the project that implements the ServiceProvider configures only the services it needs for that specific project.

I.e. if a project only needs the OpenSearch client then it should be possible to configure OpenSearch without and errors are because the rest of clients are not configured.

**Comment by guddo** [comment]
@hrmoller Please update the description and explain what is resolved.

**Comment by hrmoller** [comment]
fixed with https://github.com/DBCDK/dbc-node-serviceprovider/commit/0af7a0c3d62c8cf41c710d405ff8804c4994cdc4#diff-ecfae9a7d9bc2d491564bd0d8cd7194aL38
